export_cmd ="export AMC_API_USE=N;"


DaemonData ={   "BTLSOR":{  "LOG_FILE_PREFIX"        : "*BL1BTLSOR*" ,
                            "FAILURE_LOG_FILE_PREFIX": "*BL1BTLSOR*" ,
                            "FAILURE_LOG_FILE_PREFIX": "*BL1BTLSOR*" ,                
                            "BACKUP_LOG_FILE_PREFIX" : "*BL1BTLSOR*" ,
                            "DAEMON_DESCRIPTION"     :  "BL1BTLSOR"  ,
                            "START_COMMAND"          :  "export AMC_API_USE=N;bl1_runproc_Ksh bl1BTLServer -n BL1BTLSOR -f REGULAR" ,
                            "STOP_COMMAND"           :  "export AMC_API_USE=N;bl1_killproc_Ksh ${USER} 'bl1BTLServer -n BL1BTLSOR'" , 
                             "LOG_PASS_STR"          :  "" ,
                            "PSU_STRING"             :   "bl1BTLServer.*-n.*BL1BTLSOR.*-f.*REGULAR" },
                            
               "BTLQUOTE":{ "LOG_FILE_PREFIX"        :  "*BTLQUOTE*" ,
                            "FAILURE_LOG_FILE_PREFIX":  "*BTLQUOTE*" ,
                            "BACKUP_LOG_FILE_PREFIX" :  "*BTLQUOTE*" ,
                            "DAEMON_DESCRIPTION"     :  "BTLQUOTE"   ,
                            "START_COMMAND"          :  "export AMC_API_USE=N;bl1_runproc_Ksh bl1BTLServer -n BTLQUOTE -f REGULAR" ,
                            "STOP_COMMAND"           :  "export AMC_API_USE=N;bl1_killproc_Ksh ${USER} 'bl1BTLServer -n BTLQUOTE'"  ,
                            "LOG_PASS_STR"           :  "" ,
                            "PSU_STRING"             :  "bl1BTLServer.*-n.*BTLQUOTE.*-f.*REGULAR" },

                "TRB":     { "LOG_FILE_PREFIX"       : "TRB1*" ,
                            "LOG_LOCATION"           :  "${ABP_TRB_ROOT}/log/MSD",
                            "FAILURE_LOG_FILE_PREFIX":  "TRB1*" ,
                            "FAILURE_LOG_LOCATION"   :  "${ABP_TRB_ROOT}/log/MSD",
                            "BACKUP_LOG_LOCATION"    :  "${ABP_TRB_ROOT}/log/MSD",
                            "BACKUP_LOG_FILE_PREFIX" :  "TRB1*" ,
                            "DAEMON_DESCRIPTION"     :  "TRB_MANAGER",   
                            "START_COMMAND"          :  "TRB1RunManager_Sh -e 1 -r PR" ,
                            "STOP_COMMAND"           :  "TRB1StopManager_Sh \"\${STOP_MSD}\" -t"  ,
                            "LOG_PASS_STR"           :  "",
                            "PSU_STRING"             :  "TRB1Manager 1 PR" },

                "AMC_SERVER":{
                            "LOG_LOCATION"           :  "${ABP_TRB_ROOT}/log/MSD",
                            "LOG_FILE_PREFIX"        : "amc-out.log",
                            "LOG_LOCATION"           :  "${MON_LOG_DIR}",                            
                            "DAEMON_DESCRIPTION"     :  "AMC_SERVER",   
                            "START_COMMAND"          :  "Amc Start" ,
                            "STOP_COMMAND"           :  "Amc Stop"  ,
                            "PSU_STRING"             :  "DAMC_CONNECTION_ID" ,
                            "LOG_PASS_STR"           :  "Processes configuration completed." }     ,

                "AMC_DAEMON_MANAGER":{
                            "LOG_LOCATION"           :  "~/Automation/logs",
                            "LOG_FILE_PREFIX"        :  "AMC_DAEMON_MANAGER__${UniqeString}*",
                            "LOG_LOCATION"           :  "~/Automation/logs", 
                            "FAILURE_LOG_FILE_PREFIX":  "*AMC_DAEMON_MANAGER_${UniqeString}*" ,
                            "FAILURE_LOG_LOCATION"   :  "~/Automation/logs",  
                            "BACKUP_LOG_LOCATION"    :  "",
                            "BACKUP_LOG_FILE_PREFIX" :  "" ,                                                     
                            "DAEMON_DESCRIPTION"     :  "AMC_DAEMON_MANAGER",   
                            "START_COMMAND"          :  "export AMC_API_USE=Y;amc1_DmnEnv -c Start -f amc1_Daemon_$USER.xml -u $USER -t AMC" ,
                            "STOP_COMMAND"           :  "export AMC_API_USE=Y;amc1_DmnEnv -c Stop -f amc1_Daemon_$USER.xml -u $USER -t AMC"  ,
                            "PSU_STRING"             :  "DmnMng" ,
                            "LOG_PASS_STR"           :  "amc1_DaemonManager Started" }     ,               
                
                "MRO":     { "LOG_FILE_PREFIX"       :  "*MRO_*" ,
                            "LOG_LOCATION"           :  "~/Automation/logs",
                            "FAILURE_LOG_FILE_PREFIX":  "*MRO_*" ,
                            "FAILURE_LOG_LOCATION"   :  "~/Automation/logs",
                            "BACKUP_LOG_LOCATION"    :  "",
                            "BACKUP_LOG_FILE_PREFIX" :  "" ,
                            "DAEMON_DESCRIPTION"     :  "MRO",   
                            "START_COMMAND"          :  "Start_LocalMro ${AMC_HOME} ${USER}" ,
                            "STOP_COMMAND"           :  "Stop_LocalMro ${USER}"  ,
                            "PSU_STRING"             :  "amc_mro" ,
                            "LOG_PASS_STR"           :  "1 MROs have been started" ,
                            "TIMEOUT"                :  60                 },
  
                                
                "INVOKER1":     { "LOG_FILE_PREFIX"       :  "*TLS1_APInvoker*" ,
                            "LOG_LOCATION"           :  "${ABP_TLS_ROOT}/log/APInvoker_1",
                            "FAILURE_LOG_FILE_PREFIX":  "*TLS1_APInvoker*" ,
                            "FAILURE_LOG_LOCATION"   :  "${ABP_TLS_ROOT}/log/APInvoker_1",
                            "BACKUP_LOG_LOCATION"    :  "${ABP_TLS_ROOT}/log/APInvoker_1",
                            "BACKUP_LOG_FILE_PREFIX" :  "*" ,
                            "DAEMON_DESCRIPTION"     :  "API_INVOKER_1",   
                            "START_COMMAND"          :  "TLS1RunAPInvoker_Sh -n 1 -r 1" ,
                            "STOP_COMMAND"           :  "TLS1StopAPInvoker_Sh -n 1 -r 1"  ,
                            "PSU_STRING"             :  "amc1_DmnEnvelope.*TLS1_APInvoker_1_1" ,
                            "LOG_PASS_STR"           :  "Execution ended successfully" , 
                            "TIMEOUT"                :  60                 }  ,                         
         
                                
                "INVOKER2":     { "LOG_FILE_PREFIX"       :  "*TLS1_APInvoker*" ,
                            "LOG_LOCATION"           :  "${ABP_TLS_ROOT}/log/APInvoker_2",
                            "FAILURE_LOG_FILE_PREFIX":  "*TLS1_APInvoker*" ,
                            "FAILURE_LOG_LOCATION"   :  "${ABP_TLS_ROOT}/log/APInvoker_2",
                            "BACKUP_LOG_LOCATION"    :  "${ABP_TLS_ROOT}/log/APInvoker_2",
                            "BACKUP_LOG_FILE_PREFIX" :  "*" ,
                            "DAEMON_DESCRIPTION"     :  "API_INVOKER_2",   
                            "START_COMMAND"          :  "TLS1RunAPInvoker_Sh -n 2 -r 1" ,
                            "STOP_COMMAND"           :  "TLS1StopAPInvoker_Sh -n 2 -r 1"  ,
                            "PSU_STRING"             :  "amc1_DmnEnvelope.*TLS1_APInvoker_2_1" ,
                            "LOG_PASS_STR"           :  "Execution ended successfully",
                            "TIMEOUT"                :  60                 },                            
          
                  
                                             
                "INVOKER10":     { "LOG_FILE_PREFIX"       :  "*TLS1_APInvoker*" ,
                            "LOG_LOCATION"           :  "${ABP_TLS_ROOT}/log/APInvoker_10",
                            "FAILURE_LOG_FILE_PREFIX":  "*TLS1_APInvoker*" ,
                            "FAILURE_LOG_LOCATION"   :  "${ABP_TLS_ROOT}/log/APInvoker_10",
                            "BACKUP_LOG_LOCATION"    :  "${ABP_TLS_ROOT}/log/APInvoker_10",
                            "BACKUP_LOG_FILE_PREFIX" :  "*" ,
                            "DAEMON_DESCRIPTION"     :  "API_INVOKER_10",   
                            "START_COMMAND"          :  "TLS1RunAPInvoker_Sh -n 10 -r 1" ,
                            "STOP_COMMAND"           :  "TLS1StopAPInvoker_Sh -n 10 -r 1"  ,
                            "PSU_STRING"             :  "amc1_DmnEnvelope.*TLS1_APInvoker_10_1" ,
                            "LOG_PASS_STR"           :  "Execution ended successfully",
                            "TIMEOUT"                :  60                 },  
            
                "AR1BILINTER": { "LOG_FILE_PREFIX"   :  "*AR1BILINTER_${UniqeString}*" ,
                            "LOG_LOCATION"           :  "~/Automation/logs",
                            "FAILURE_LOG_FILE_PREFIX":  "*AR1BILINTER*" ,
                            "FAILURE_LOG_LOCATION"   :  "${OP_LOG_DIR}",
                            "BACKUP_LOG_LOCATION"    :  "*AR1BILINTER*",
                            "BACKUP_LOG_FILE_PREFIX" :  "${OP_LOG_DIR}" ,
                            "DAEMON_DESCRIPTION"     :  "AR1BILINTER",   
                            "START_COMMAND"          :  "export AR_RUN_MODE=AMC;ar1_BillPrepInterface_Sh AR1BILINTER AR1DAEMON 01 5 5" ,
                            "STOP_COMMAND"           :  "export AR_RUN_MODE=AMC;ar1_stopDaemon_Sh AR1BILINTER AR1DAEMON 01"  ,
                            "PSU_STRING"             :  "amc1_DmnEnvelope.*AR1BILINTER_01" ,
                            "LOG_PASS_STR"           :  "Execution ended successfully",
                            "TIMEOUT"                :  10                },                            
                         
                "RQSLSNR": { "LOG_FILE_PREFIX"   :  "*RQSLSNR*" ,
                            "LOG_LOCATION"           :  "${ABP_BL_ROOT}/log",
                            "FAILURE_LOG_FILE_PREFIX":  "*RQSLSNR*" ,
                            "FAILURE_LOG_LOCATION"   :  "${OP_LOG_DIR}",
                            "BACKUP_LOG_LOCATION"    :  "${ABP_BL_ROOT}/log",
                            "BACKUP_LOG_FILE_PREFIX" :  "*RQSLSNR*" ,
                            "DAEMON_DESCRIPTION"     :  "RQSLSNR",   
                            "START_COMMAND"          :  "export AMC_API_USE=Y;bl1_runproc_Ksh bl1rqslsnr -e RQSLSNR" ,
                            "STOP_COMMAND"           :  "export AMC_API_USE=N;bl1_killproc_Ksh ${USER} 'bl1rqslsnr -e RQSLSNR'"  ,
                            "PSU_STRING"             :  "bl1rqslsnr.*-e.*RQSLSNR" ,
                            "LOG_PASS_STR"           :  "AMC Acceptor Receiving started for AMC",
                            "TIMEOUT"                :  60               }, 
                "BLBDI": { "LOG_FILE_PREFIX"   :  "*BLBDI*" ,
                            "LOG_LOCATION"           :  "${ABP_BL_ROOT}/log",
                            "FAILURE_LOG_FILE_PREFIX":  "*BLBDI*" ,
                            "FAILURE_LOG_LOCATION"   :  "${OP_LOG_DIR}",
                            "BACKUP_LOG_LOCATION"    :  "${ABP_BL_ROOT}/log",
                            "BACKUP_LOG_FILE_PREFIX" :  "*BLBDI*" ,
                            "DAEMON_DESCRIPTION"     :  "BLBDI",   
                            "START_COMMAND"          :  "" ,
                            "STOP_COMMAND"           :  ""  ,
                            "PSU_STRING"             :  "BLBDI" ,
                            "LOG_PASS_STR"           :  "AMC Acceptor Receiving started for AMC",
                            "TIMEOUT"                :  60               }
             }             

      
